### PR TITLE
feature(ticketing) : adding ticketing on presentation page

### PR DESCRIPTION
**Pull request by florianroulet**

### CODE REVIEW

**Comment by florianroulet** [comment]
@jollivetc pas con, j'ai juste repris la phrase précédemment présente et ajouté le lien.

**Comment by CedricGatay** [comment]
I agree with @jollivetc, I think we can either remove the "Pour cette première" wording or change the wording to "Pour cette première édition, nous accueillerons 250 personnes." A big signup button can be nice too, but I do not know what our design team is thinking :)

**Comment by florianroulet** [comment]
I'm quite afraid of displaying the number of places availables. It may be counterproductive as people will see that a lot of places are available, and wait for the last moment. I think for this edition/year, we can communicate only on social network on this information. As I told, this is only fear. Maybe we should display it, debate opened !

**Comment by CedricGatay** [comment]
I do not consider 250 slots to be a lot, so I tend to think like @jollivetc : "I should hurry!". Anyway, removing it is not big deal to me.

**Comment by jollivetc** [comment]
Anyway, the number of places left is shown at the top of the helloasso website.

**Pull request merged**
