### PR TITLE
feat(planning): planning 2022

### PR DESCRIPTION
**Pull request by vmaerten**

### CODE REVIEW

**Comment by vmaerten** [comment]
Do not merge before you get all confirmation from all speakers

**Comment by CedricGatay** [comment]
On Friday the third column is way too large, is there anyway to fix this @vmaerten ?

**Comment by vmaerten** [comment]
Do you have any cache ?

**Comment by vmaerten** [comment]
Good catch ! 
Should be fixed now, could you check again ? I do not reproduce with the fix

**Comment by CedricGatay** [comment]
Way better, there is still a slight difference in places header's height between Thursday and Friday thought. I don't know if it is easy to fix

**Comment by vmaerten** [comment]
What about now ?

**Comment by CedricGatay** [comment]
LGTM

**Comment by CedricGatay** [comment]
A few comments :
 
 * we barely see on which day we're on when viewing the program (maybe change alpha for unselected item ?)
 * conferences titles are truncated, we need to set the word-wrapping so that it does not happen
 * on talk detail page, we do not have date / time and room

**Comment by vmaerten** [comment]
> we barely see on which day we're on when viewing the program (maybe change alpha for unselected item ?)
I made a proposal !
> conferences titles are truncated, we need to set the word-wrapping so that it does not happen
Done

I'll add time room on talks' page later

**Comment by CedricGatay** [comment]
LGTM, even if it is for 2023 and not 2022 ;)

**Pull request merged**
